# Generated by Django 4.1.5 on 2023-01-09 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=8, max_length=8, prefix='', primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('first_line_address', models.CharField(max_length=255)),
                ('second_line_address', models.CharField(max_length=255)),
                ('postocde', models.CharField(max_length=255)),
                ('town_or_city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lease_agreement_file', models.FileField(upload_to='')),
                ('rent_protection_policy_file', models.FileField(upload_to='')),
                ('tenant_vetting_file', models.FileField(upload_to='')),
                ('amount_of_rent_selling', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_monthly_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name_on_bank_account', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('sort_code_bank_account', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
