# Generated by Django 4.1.5 on 2023-01-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='admin_comment',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
