# Generated by Django 4.1.5 on 2023-01-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_has_address_history_user_is_identity_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_history_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
    ]
