# Generated by Django 4.1.5 on 2023-01-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_address_history_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advance',
            old_name='postocde',
            new_name='postcode',
        ),
    ]
