# Generated by Django 4.1.5 on 2023-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_postocde_advance_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='reason',
            field=models.TextField(default='', max_length=100),
        ),
    ]
