# Generated by Django 4.1.5 on 2023-01-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_advance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789', editable=False, length=8, max_length=8, prefix='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='AddressHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_line_address', models.CharField(max_length=255)),
                ('second_line_address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('town_or_city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
