# Generated by Django 4.1.5 on 2023-01-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_advance_id_addresshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_address_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addresshistory',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
