# Generated by Django 4.1.5 on 2023-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_amount_of_rent_selling_advance_estimated_loan_monthly_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='loan_interest_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='advance',
            name='loan_term',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advance',
            name='remaining_term',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advance',
            name='total_paid_already',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='advance',
            name='total_repayble',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='advance',
            name='estimated_loan_monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='advance',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='advance',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
