# Generated by Django 4.1.5 on 2023-01-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_advance_loan_interest_rate_advance_loan_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
