# Generated by Django 4.1.5 on 2023-01-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_advance_next_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advance',
            name='next_payment_date',
        ),
    ]
