# Generated by Django 4.1.5 on 2023-01-16 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_advance_next_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
