# Generated by Django 4.1.5 on 2023-01-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_advance_created_on_advance_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Submitted', 'Submitted'), ('Active', 'Active'), ('In arrears', 'In arrears'), ('Repaid', 'Repaid')], default='Incomplete', max_length=16),
        ),
    ]
