# Generated by Django 4.1.5 on 2023-01-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_advance_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='loan_term',
            field=models.PositiveIntegerField(choices=[(3, '3 months'), (6, '6 months'), (12, '12 months'), (24, '24 months'), (36, '36 months'), (48, '48 months'), (60, '60 months')], default=3),
        ),
    ]
