# Generated by Django 4.1.5 on 2023-01-18 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_advance_reason_alter_advance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(2999)]),
        ),
        migrations.AlterField(
            model_name='advance',
            name='reason',
            field=models.CharField(choices=[('Consolidating debt', 'Consolidating debt'), ('Home improvement/repair', 'Home improvement/repair'), ('Car finacing', 'Car finacing'), ('Special occasion/event', 'Special occasion/event'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
