# Generated by Django 4.1.5 on 2023-01-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_advance_loan_amount_alter_advance_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='is_submitting_loan',
            field=models.BooleanField(default=False),
        ),
    ]
