# Generated by Django 4.1.5 on 2023-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_advance_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='lease_agreement_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advance',
            name='loan_interest_rate',
            field=models.FloatField(choices=[(0.2399, '23.99%'), (0.2199, '21.99%'), (0.1999, '19.99%'), (0.1799, '17.99%'), (0.1599, '15.99%'), (0.1399, '13.99%'), (0.1299, '12.99%')], default=0.2399),
        ),
    ]
