# Generated by Django 4.1.5 on 2023-01-23 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_scheduledpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='lease_agreement_file',
            field=models.FileField(blank=True, default=uuid.uuid4, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advance',
            name='rent_protection_policy_file',
            field=models.FileField(blank=True, default=uuid.uuid4, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advance',
            name='tenant_vetting_file',
            field=models.FileField(blank=True, default=uuid.uuid4, null=True, upload_to=''),
        ),
    ]
