# Generated by Django 4.1.5 on 2023-01-23 18:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_advance_lease_agreement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='lease_agreement_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.Advance.get_path),
        ),
        migrations.AlterField(
            model_name='advance',
            name='rent_protection_policy_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.Advance.get_path),
        ),
        migrations.AlterField(
            model_name='advance',
            name='tenant_vetting_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.Advance.get_path),
        ),
    ]
