# Generated by Django 4.1.5 on 2023-02-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_advance_annualised_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='annualised_fee',
            field=models.FloatField(choices=[(0.1289, '12.89%'), (0.1166, '11.66%'), (0.1065, '10.65%'), (0.0962, '9.62%'), (0.0854, '8.54%')], default=0),
        ),
    ]
