# Generated by Django 4.1.5 on 2023-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_advance_annualised_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='second_line_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
