# Generated by Django 4.1.5 on 2023-02-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_advance_second_line_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_address_verified',
            field=models.BooleanField(default=False),
        ),
    ]
