# Generated by Django 4.1.5 on 2023-01-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_advance_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_address_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
