# Generated by Django 4.1.5 on 2023-01-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_total_address_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advance',
            old_name='amount_of_rent_selling',
            new_name='estimated_loan_monthly_payment',
        ),
        migrations.RenameField(
            model_name='advance',
            old_name='estimated_monthly_payment',
            new_name='loan_amount',
        ),
    ]
