# Generated by Django 4.1.5 on 2023-01-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_advance_is_submitting_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending approval', 'Pending approval'), ('Active', 'Active'), ('In arrears', 'In arrears'), ('Repaid', 'Repaid')], default='Incomplete', max_length=25),
        ),
    ]
